version: "3.6"
services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "ionic serve --host 0.0.0.0"  # wait for db, then run
    container_name: frontend
    ports:
      - 8100:8100


  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 3000:80
    depends_on:
      - frontend